version: "3.9"

networks:
  default:
    external: true
    name: nginx_proxy_network

services:
  app:
    build: .
    tty: true
    container_name: ${PROJECT}_app
    volumes:
      - ./:/usr/src/app
    # ports:
    #   - "80:3000"
    restart: always
