version: "3.9"

networks:
  default:
    external: true
    name: reup_server_default

services:
  app:
    build: .
    tty: true
    container_name: ${PROJECT}_app
    volumes:
      - ./:/usr/src/app
    ports:
      - "8888:3000"
    restart: always
