import Head from "next/head";
import MainLayout from "../components/layout";
import { ThemeProvider } from "next-themes";
import { ChainId, ThirdwebProvider, embeddedWallet,
  metamaskWallet,
  coinbaseWallet,
  walletConnect,
} from "@thirdweb-dev/react";
// GLOBAL STYLES
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/fonts.sass";
import "../styles/global.sass";

// GLOBAL SCRIPTS

const activeChain = ChainId.BinanceSmartChainTestnet;

function MyApp({ Component, pageProps }) {
  return (
    <>
    <ThirdwebProvider ChainId={activeChain} 
    clientId="e4f5177379735ef6579ee23a5a48bbc1"
    supportedWallets={[        metamaskWallet({
      recommended: true,
    }),
    coinbaseWallet(),
    walletConnect(),
]}
    >
      <Head>
        <title>TTM | TO THE MOON</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider defaultTheme={"dark"} enableSystem={false}>
        <MainLayout>
          <Component {...pageProps} />
        </MainLayout>
      </ThemeProvider>
      </ThirdwebProvider>
    </>
  );
}

export default MyApp;
