
export default function handler(req: any, res: any) {
    const { id } = req.query
    const domain = process.env.NEXT_PUBLIC_DOMAIN
    const nftCollection: any = {
        0: { Name: "Galactic Passion", Short_Description: "Passion burning bright in the heart of the galaxy." },
        1: { Name: "Lunar Lullaby", Short_Description: "A soothing melody to accompany your journey through the stars." },
        2: { Name: "Galactic Greetings", Short_Description: "Friendly messages exchanged across the cosmos." },
        3: { Name: "Stellar Sparkle", Short_Description: "Shimmering with the brilliance of a thousand stars." },
        4: { Name: "Cosmic Charmer", Short_Description: "Captivating all who venture into the void." },
        5: { Name: "Nebula Nuzzler", Short_Description: "Cuddly companion on interstellar voyages." },
        6: { Name: "Astronaut's Anthem", Short_Description: "The soundtrack of space exploration." },
        7: { Name: "Orbiting Opus", Short_Description: "A musical masterpiece echoing through the cosmos." },
        8: { Name: "Celestial Cuddle", Short_Description: "Wrapped in the warmth of cosmic love." },
        9: { Name: "Astro Adornment", Short_Description: "Gleaming with futuristic elegance." },
        10: { Name: "Stardust Symphony", Short_Description: "Harmonies woven from the fabric of the universe." },
        11: { Name: "Lunar Luminance", Short_Description: "Radiant glow illuminating the darkest corners of space." },
        12: { Name: "Galactic Grace", Short_Description: "Elegant beauty spanning light-years." },
        13: { Name: "Astronaut's Ascent", Short_Description: "Rising to new heights among the stars." },
        14: { Name: "Cosmic Carousel", Short_Description: "Whirling through the galaxy on a cosmic ride." },
        15: { Name: "Nebula Nebulae", Short_Description: "Exploring the colorful clouds of distant worlds." },
        16: { Name: "Stellar Serenade", Short_Description: "Serenading the universe with celestial melodies." },
        17: { Name: "Space Suit Sweetheart", Short_Description: "Love blossoming in the vacuum of space." },
        18: { Name: "Astronaut's Affection", Short_Description: "Heartfelt emotions expressed across the cosmos." },
        19: { Name: "Galactic Guardian", Short_Description: "Protecting the universe with unwavering resolve." },
        20: { Name: "Lunar Lullaby", Short_Description: "A soothing melody to accompany your journey through the stars." },
        21: { Name: "Stellar Snuggle", Short_Description: "Cuddling beneath the canopy of the Milky Way." },
        22: { Name: "Cosmic Kisses", Short_Description: "Whispers of love carried on cosmic winds." },
        23: { Name: "Asteroid Amour", Short_Description: "Romance amidst the rubble of the asteroid belt." },
        24: { Name: "Nebula's Embrace", Short_Description: "Wrapped in the ethereal glow of interstellar gas." },
        25: { Name: "Galactic Giggle", Short_Description: "Laughter echoing through the vastness of space." },
        26: { Name: "Starlight Serenade", Short_Description: "Love songs sung under the light of distant stars." },
        27: { Name: "Cosmic Connection", Short_Description: "Bonds that transcend time and space." },
        28: { Name: "Lunar Lovebird", Short_Description: "Mates for life, soaring through the lunar landscape." },
        29: { Name: "Stellar Sweetheart", Short_Description: "Two hearts entwined in the cosmic dance." },
        30: { Name: "Astro Affection", Short_Description: "Love that spans the expanse of the universe." },
        31: { Name: "Cosmic Courting", Short_Description: "Courtship rituals under alien skies." },
        32: { Name: "Nebula Nuptials", Short_Description: "Cosmic weddings among the stars." },
        33: { Name: "Galactic Romance", Short_Description: "Love stories written in the stars." },
        34: { Name: "Celestial Courtship", Short_Description: "Romance blossoming in the celestial realm." },
        35: { Name: "Astronaut's Amour", Short_Description: "Love that defies the gravity of ordinary life." },
        36: { Name: "Stellar Soulmates", Short_Description: "Two souls united by the cosmos." },
        37: { Name: "Space Sweethearts", Short_Description: "Lovebirds soaring through the cosmic void." },
        38: { Name: "Lunar Lover", Short_Description: "Moonlit rendezvous on the surface of the moon." },
        39: { Name: "Galactic Gaze", Short_Description: "Lost in each other's eyes amid the stars." },
        40: { Name: "Nebula Nuzzle", Short_Description: "Snuggling amidst the swirling gas clouds of a nebula." },
        41: { Name: "Stellar Soulmate", Short_Description: "A love that burns as bright as a supernova." },
        42: { Name: "Astronaut's Ardor", Short_Description: "Passion ignited in the zero-gravity of space." },
        43: { Name: "Cosmic Cuddle", Short_Description: "Wrapped in the warmth of a cosmic embrace." },
        44: { Name: "Lunar Longing", Short_Description: "Yearning for love under the pale light of the moon." },
        45: { Name: "Galactic Embrace", Short_Description: "Holding each other close in the vastness of space." },
        46: { Name: "Nebula's Kiss", Short_Description: "Soft caresses beneath the colorful hues of a nebula." },
        47: { Name: "Stellar Stargazer", Short_Description: "Gazing at the stars together, dreaming of forever." },
        48: { Name: "Astro Affinity", Short_Description: "Cosmic chemistry that's out of this world." },
        49: { Name: "Space Sweetheart", Short_Description: "Whispers of love in the silent void of space." },
        50: { Name: "Celestial Connection", Short_Description: "Soulmates connected by the threads of the universe." },
        51: { Name: "Lunar Love", Short_Description: "Romance blossoming under the glow of the moon." },
        52: { Name: "Galactic Devotion", Short_Description: "A love that spans the vast expanse of the cosmos." },
        53: { Name: "Nebula's Embrace", Short_Description: "Enveloped in the swirling colors of a distant nebula." },
        54: { Name: "Stellar Serenity", Short_Description: "Tranquility found in the depths of space." },
        55: { Name: "Astro Adoration", Short_Description: "Worshiping at the altar of cosmic love." },
        56: { Name: "Cosmic Courtship", Short_Description: "The dance of love beneath the stars." },
        57: { Name: "Lunar Luminescence", Short_Description: "Radiant love glowing in the darkness of space." },
        58: { Name: "Galactic Glow", Short_Description: "Love shining brightly across the galaxy." },
        59: { Name: "Nebula's Nocturne", Short_Description: "Whispers of love in the cosmic night." },
        60: { Name: "Stellar Swoon", Short_Description: "Swooning under the spell of the stars." },
        61: { Name: "Astro Amore", Short_Description: "Love that's written in the stars." },
        62: { Name: "Cosmic Caress", Short_Description: "Tender touches in the vastness of space." },
        63: { Name: "Lunar Lustre", Short_Description: "The glow of love reflected in the moonlight." },
        64: { Name: "Galactic Glimmer", Short_Description: "Sparkling with the light of a thousand galaxies." },
        65: { Name: "Nebula's Whisper", Short_Description: "Secrets shared in the silence of the cosmos." },
        66: { Name: "Stellar Surrender", Short_Description: "Surrendering to love under the starry sky." },
        67: { Name: "Astro Affair", Short_Description: "A passionate romance among the stars." },
        68: { Name: "Cosmic Connection", Short_Description: "Two souls linked by the cosmic web." },
        69: { Name: "Lunar Lovers", Short_Description: "Love that blossoms in the shadow of the moon." },
        70: { Name: "Galactic Passion", Short_Description: "Passion burning bright in the heart of the galaxy." },
        71: { Name: "Nebula's Embrace", Short_Description: "Embraced by the swirling colors of a distant nebula." },
        72: { Name: "Stellar Symphony", Short_Description: "The music of love echoing through the universe." },
        73: { Name: "Astro Amour", Short_Description: "Love that spans the cosmos." },
        74: { Name: "Cosmic Cadence", Short_Description: "Dancing to the rhythm of the stars." },
        75: { Name: "Lunar Luminary", Short_Description: "Love shining bright in the darkness of space." },
        76: { Name: "Galactic Gleam", Short_Description: "Radiant love lighting up the galaxy." },
        77: { Name: "Nebula's Glow", Short_Description: "Bathed in the ethereal glow of a distant nebula." },
        78: { Name: "Stellar Stroll", Short_Description: "Walking hand in hand under the starry sky." },
        79: { Name: "Astro Adoration", Short_Description: "Adoring each other under alien skies." },
        80: { Name: "Cosmic Connection", Short_Description: "Connected by the cosmic threads of fate." },
        81: { Name: "Lunar Lovebirds", Short_Description: "Lovebirds soaring through the moonlit sky." },
        82: { Name: "Galactic Grace", Short_Description: "Graceful love spanning light-years." },
        83: { Name: "Nebula's Embrace", Short_Description: "Enveloped in the swirling colors of a distant nebula." },
        84: { Name: "Stellar Serenity", Short_Description: "Serenity found in the depths of space." },
        85: { Name: "Astro Amour", Short_Description: "Love that transcends time and space." },
        86: { Name: "Cosmic Caress", Short_Description: "Tender caresses in the cosmic void." },
        87: { Name: "Lunar Luminescence", Short_Description: "Radiant love glowing in the darkness of space." },
        88: { Name: "Galactic Glow", Short_Description: "Love shining brightly across the galaxy." },
        89: { Name: "Nebula's Nocturne", Short_Description: "Whispers of love in the cosmic night." },
        90: { Name: "Stellar Swoon", Short_Description: "Swooning under the spell of the stars." },
        91: { Name: "Astro Amore", Short_Description: "Love that's written in the stars." },
        92: { Name: "Cosmic Caress", Short_Description: "Tender touches in the vastness of space." },
        93: { Name: "Lunar Lustre", Short_Description: "The glow of love reflected in the moonlight." },
        94: { Name: "Galactic Glimmer", Short_Description: "Sparkling with the light of a thousand galaxies." },
        95: { Name: "Nebula's Whisper", Short_Description: "Secrets shared in the silence of the cosmos." },
        96: { Name: "Stellar Surrender", Short_Description: "Surrendering to love under the starry sky." },
        97: { Name: "Astro Affair", Short_Description: "A passionate romance among the stars." },
        98: { Name: "Cosmic Connection", Short_Description: "Two souls linked by the cosmic web." },
        99: { Name: "Lunar Lovers", Short_Description: "Love that blossoms in the shadow of the moon." },
    };
    let data = {
        // image: `${domain}/static/assets/images/nft-cards/${id}.jpg`,
        // image: "/_next/image?url=%2Fstatic%2Fassets%2Fimages%2Fnft-cards%2F4.jpg&w=3840&q=100",
        image: `https://bafybeig3phu3eerivm63mnhubyf37i67i2oile76lomujftzjlyjy6d4zm.ipfs.nftstorage.link/Astro%20(${id}).png`,
        name: nftCollection[id].Name + id,
        designer: 'Minamoto',
        tokenId: id,
        description: nftCollection[id].Short_Description,

    }

    res.status(200).json(data);
}